# Generated by Django 3.1.7 on 2021-03-05 17:50

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('user_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('gender', django_mysql.models.EnumField(choices=[('M', 'M'), ('F', 'F'), ('Other', 'Other')])),
                ('ph_no', models.CharField(max_length=10)),
                ('par_ph_no', models.CharField(max_length=10)),
                ('yoj', models.CharField(max_length=4)),
                ('dept', django_mysql.models.EnumField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('BT', 'BT'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('AERO', 'AERO'), ('CHEM', 'CHEM')])),
                ('password', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('user_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('gender', django_mysql.models.EnumField(choices=[('M', 'M'), ('F', 'F'), ('Other', 'Other')])),
                ('ph_no', models.CharField(max_length=10)),
                ('teach_ph_no', models.CharField(max_length=10)),
                ('yoj', models.CharField(max_length=4)),
                ('qualification', django_mysql.models.EnumField(choices=[('UG', 'UG'), ('PG', 'PG'), ('PHD', 'PHD')])),
                ('dept', django_mysql.models.EnumField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('BT', 'BT'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('AERO', 'AERO'), ('CHEM', 'CHEM')])),
                ('password', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'teacher',
                'managed': True,
            },
        ),
    ]
